import { expect, test } from '@playwright/test'

test('clean chat shell and settings remain usable', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByText('How can I help')).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Settings' })).toBeVisible()
  await page.getByRole('button', { name: 'Settings' }).click()
  await expect(page.getByRole('dialog', { name: 'Settings' })).toBeVisible()
  const dialog = page.getByRole('dialog', { name: 'Settings' })
  await expect(dialog.getByRole('tab', { name: /Model & runtime/ })).toBeVisible()
  const viewport = page.viewportSize()
  await expect.poll(async () => {
    const box = await dialog.boundingBox()
    return Boolean(box && box.width >= viewport.width - 2 && box.height >= viewport.height - 2)
  }).toBe(true)
  await dialog.getByRole('tab', { name: /MCP servers/ }).click()
  await expect(page.getByRole('button', { name: 'New MCP server' })).toBeVisible()
  await expect(page.getByText('Local, permission-controlled connections')).toBeVisible()
  const gmail = dialog.getByRole('button', { name: /Add Gmail account/ })
  await expect(gmail).toBeVisible()
  await gmail.click()
  await expect(dialog.getByRole('textbox', { name: 'Account name' })).toBeVisible()
  await expect(dialog.getByRole('button', { name: 'Save account' })).toBeDisabled()
})

test('chat sidebar and mobile drawer fit the viewport', async ({ page }) => {
  await page.goto('/')
  const viewport = page.viewportSize()
  if (viewport.width >= 768) {
    const sidebar = page.getByRole('complementary', { name: 'Chat history' })
    await expect(sidebar).toBeVisible()
    await expect(sidebar.getByRole('button', { name: 'New chat' })).toBeVisible()
    await sidebar.getByRole('button', { name: 'Hide chat sidebar' }).click()
    await expect(sidebar).toBeHidden()
    await page.getByRole('button', { name: 'Show chat sidebar' }).click()
    await expect(sidebar).toBeVisible()
  } else {
    await page.getByRole('button', { name: 'Open chats' }).click()
    const dialog = page.getByRole('dialog', { name: 'Chats' })
    await expect(dialog).toBeVisible()
    await expect.poll(async () => {
      const box = await dialog.boundingBox()
      return Boolean(box && box.x >= 0 && box.x + box.width <= viewport.width + 1)
    }).toBe(true)
    const drawer = await dialog.boundingBox()
    expect(drawer.x).toBeGreaterThanOrEqual(0)
    expect(drawer.x + drawer.width).toBeLessThanOrEqual(viewport.width)
    await dialog.getByRole('button', { name: 'Close' }).click()
  }
  const composerInput = page.getByLabel('Message Local AI')
  await expect(composerInput).toBeVisible()
  await expect.poll(() => composerInput.evaluate(element => {
    const inputStyle = getComputedStyle(element)
    const composerStyle = getComputedStyle(element.closest('.composer'))
    return [inputStyle.borderWidth, inputStyle.boxShadow, composerStyle.borderWidth]
  })).toEqual(['0px', 'none', '0px'])
})

test('files can be attached, indexed, shown, and removed', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Add files or folders' }).click()
  await expect(page.getByText('Folder', { exact: true })).toBeVisible()
  await page.keyboard.press('Escape')
  const picker = page.locator('input[type="file"]:not([webkitdirectory])')
  await picker.setInputFiles({
    name: 'project-notes.md',
    mimeType: 'text/markdown',
    buffer: Buffer.from('The launch checklist owner is Riverstone.'),
  })
  await expect(page.getByText('1 file indexed')).toBeVisible()
  await expect(page.getByText('project-notes.md', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Remove project-notes.md' }).click()
  await expect(page.getByText('project-notes.md', { exact: true })).toHaveCount(0)
})

test('light and dark themes are available and persist', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Theme' }).click()
  await page.getByText('Dark', { exact: true }).click()
  await expect.poll(() => page.evaluate(() => localStorage.getItem('local-ai-color-mode'))).toBe('night')
  await page.reload()
  await expect.poll(() => page.evaluate(() => localStorage.getItem('local-ai-color-mode'))).toBe('night')
  await page.getByRole('button', { name: 'Theme' }).click()
  await page.getByText('Light', { exact: true }).click()
  await expect.poll(() => page.evaluate(() => localStorage.getItem('local-ai-color-mode'))).toBe('day')
})

test('advanced local settings are accessible and responsive', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Settings' }).click()
  const dialog = page.getByRole('dialog', { name: 'Settings' })
  await dialog.getByRole('tab', { name: /Workspaces/ }).click()
  await expect(dialog.getByRole('heading', { name: 'Approved workspaces' })).toBeVisible()
  await expect(dialog.getByText('Only folders you explicitly approve can be used for repository context or Cloud handoff.')).toBeVisible()
  await expect(dialog.getByRole('textbox', { name: 'Workspace name' })).toHaveAttribute('placeholder', 'My project')
  await expect(dialog.getByRole('textbox', { name: 'Project folder' })).toHaveAttribute('placeholder', /Projects[\\/]my-project$/)
  await dialog.getByRole('tab', { name: /Activity/ }).click()
  await expect(dialog.getByRole('heading', { name: 'MCP activity' })).toBeVisible()
  await dialog.getByRole('tab', { name: /Performance/ }).click()
  await expect(dialog.getByRole('heading', { name: 'Host & performance' })).toBeVisible()
  await expect(dialog.getByRole('button', { name: 'Apply best settings for this computer' })).toBeVisible()
  await expect(dialog.getByText('Average speed')).toBeVisible()
  await expect(dialog.getByRole('heading', { name: 'Performance presets' })).toBeVisible()
  await expect(dialog.getByRole('button', { name: /Long context/ })).toContainText('Uses more RAM or VRAM')
  await expect(dialog.getByRole('heading', { name: 'Custom performance' })).toBeVisible()
  const contextSlider = dialog.getByRole('slider', { name: 'Context window' })
  await expect(contextSlider).toBeVisible()
  await contextSlider.press('ArrowRight')
  await expect(dialog.getByRole('button', { name: 'Save custom performance' })).toBeEnabled()
  await expect(dialog.getByText('Impact estimates are directional.')).toBeVisible()
  await dialog.getByRole('tab', { name: /Backup/ }).click()
  await expect(dialog.getByText('Optional—use any length. A longer unique passphrase provides stronger protection.')).toBeVisible()
  await expect(dialog.getByRole('button', { name: 'Download encrypted backup' })).toBeEnabled()
  const box = await dialog.boundingBox()
  const viewport = page.viewportSize()
  expect(box.width).toBeLessThanOrEqual(viewport.width)
  expect(box.height).toBeLessThanOrEqual(viewport.height)
})
