import { useMemo, useState } from 'react'
import { ActionList, ActionMenu, Button, Checkbox, Flash, FormControl, Link, Select, TextInput, Textarea, ToggleSwitch } from '@primer/react'
import { CopyIcon, KeyIcon, LinkExternalIcon, PencilIcon, PlusIcon, SearchIcon, ServerIcon, SyncIcon, TrashIcon } from '@primer/octicons-react'
import { DataCard, EmptyState, Field, FormActions, SectionHeading, SubsectionHeading } from './PrimerUI.jsx'

const catalog = [
  ['Filesystem', 'Files & storage'], ['Git', 'Developer tools'], ['GitHub', 'Developer tools'], ['GitLab', 'Developer tools'], ['Docker', 'Infrastructure'], ['Kubernetes', 'Infrastructure'], ['Sentry', 'Developer tools'], ['PostgreSQL', 'Databases'], ['SQLite', 'Databases'], ['MySQL', 'Databases'], ['Redis', 'Databases'], ['Playwright', 'Web & browser'], ['Fetch / Web', 'Web & browser'], ['Brave Search', 'Search & research'], ['Exa', 'Search & research'], ['Hugging Face', 'AI & models'], ['Google Drive', 'Productivity'], ['Gmail', 'Productivity'], ['Google Calendar', 'Productivity'], ['Slack', 'Communication'], ['Microsoft 365', 'Productivity'], ['Outlook', 'Communication'], ['OneDrive', 'Files & storage'], ['SharePoint', 'Productivity'], ['Notion', 'Productivity'], ['Dropbox', 'Files & storage'], ['Box', 'Files & storage'], ['Airtable', 'Business'], ['Stripe', 'Business'], ['Salesforce', 'Business'], ['HubSpot', 'Business'], ['Linear', 'Project management'], ['Jira', 'Project management'], ['Confluence', 'Knowledge'], ['Memory', 'AI & models'], ['Sequential thinking', 'AI & models'], ['Custom server', 'Custom'],
]

const authOptions = [
  ['none', 'No authorization'], ['basic', 'Username & password (Basic)'], ['bearer', 'Bearer / personal access token'], ['api-key', 'API key header'], ['oauth-authorization-code', 'OAuth 2.1 authorization code + PKCE'], ['oauth-client-credentials', 'OAuth 2.0 client credentials'], ['custom-headers', 'Custom HTTP headers'], ['environment', 'Environment variables (stdio)'], ['mtls', 'Mutual TLS certificate'], ['aws-sigv4', 'AWS Signature V4'], ['service-account', 'Service account / private key'], ['ssh', 'SSH key or password'], ['session-cookie', 'Session cookie'],
]

const blank = { name: '', category: 'Custom', description: '', enabled: false, transport: 'streamable-http', endpoint: '', command: '', arguments: '', working_directory: '', auth_type: 'none', public_config: {}, secrets: {}, permissions: { read: true, write: false, execute: false, network: false, always_confirm: true } }

function ConfigField({ label, value, onChange, secret = false, placeholder = '', type = 'text', className = '' }) {
  return <Field label={label} className={className}><TextInput block type={secret ? 'password' : type} autoComplete={secret ? 'new-password' : 'off'} value={value || ''} onChange={event => onChange(event.target.value)} placeholder={placeholder} /></Field>
}

function AuthFields({ draft, setPublic, setSecret }) {
  const publicValue = key => draft.public_config[key] || ''
  const secretValue = key => draft.secrets[key] || ''
  const pair = (...children) => <div className="form-grid">{children}</div>
  switch (draft.auth_type) {
    case 'basic': return pair(<ConfigField key="u" label="Username" value={publicValue('username')} onChange={value => setPublic('username', value)} />, <ConfigField key="p" label="Password" secret value={secretValue('password')} onChange={value => setSecret('password', value)} />)
    case 'bearer': return pair(<ConfigField key="h" label="Token label or scope" value={publicValue('token_hint')} onChange={value => setPublic('token_hint', value)} placeholder="GitHub PAT · repo scope" />, <ConfigField key="t" label="Access token" secret value={secretValue('access_token')} onChange={value => setSecret('access_token', value)} />)
    case 'api-key': return pair(<ConfigField key="h" label="Header name" value={publicValue('header_name')} onChange={value => setPublic('header_name', value)} placeholder="X-API-Key" />, <ConfigField key="k" label="API key" secret value={secretValue('api_key')} onChange={value => setSecret('api_key', value)} />)
    case 'oauth-authorization-code': return pair(<ConfigField key="id" label="Client ID" value={publicValue('client_id')} onChange={value => setPublic('client_id', value)} />, <ConfigField key="s" label="Client secret (if required)" secret value={secretValue('client_secret')} onChange={value => setSecret('client_secret', value)} />, <ConfigField key="a" label="Authorization server / metadata URL" type="url" value={publicValue('authorization_server')} onChange={value => setPublic('authorization_server', value)} placeholder="https://auth.example.com" />, <ConfigField key="sc" label="Scopes" value={publicValue('scopes')} onChange={value => setPublic('scopes', value)} placeholder="openid profile offline_access" />, <ConfigField key="r" label="Resource / audience" value={publicValue('resource')} onChange={value => setPublic('resource', value)} />, <ConfigField key="u" label="Provider-approved redirect URI" value={publicValue('redirect_uri')} onChange={value => setPublic('redirect_uri', value)} />)
    case 'oauth-client-credentials': return pair(<ConfigField key="id" label="Client ID" value={publicValue('client_id')} onChange={value => setPublic('client_id', value)} />, <ConfigField key="s" label="Client secret" secret value={secretValue('client_secret')} onChange={value => setSecret('client_secret', value)} />, <ConfigField key="t" label="Token endpoint" type="url" value={publicValue('token_endpoint')} onChange={value => setPublic('token_endpoint', value)} />, <ConfigField key="sc" label="Scopes" value={publicValue('scopes')} onChange={value => setPublic('scopes', value)} />, <ConfigField key="r" label="Resource / audience" value={publicValue('resource')} onChange={value => setPublic('resource', value)} />)
    case 'custom-headers': return pair(<ConfigField key="n" label="Header names" value={publicValue('header_names')} onChange={value => setPublic('header_names', value)} placeholder="X-Team-ID, X-API-Key" />, <ConfigField key="v" label="Header values" secret value={secretValue('header_values')} onChange={value => setSecret('header_values', value)} />)
    case 'environment': return <Field label="Environment variables"><Textarea block rows={5} value={secretValue('environment')} onChange={event => setSecret('environment', event.target.value)} placeholder={'GITHUB_TOKEN=…\nAPI_KEY=…'} /></Field>
    case 'mtls': return pair(<ConfigField key="c" label="Client certificate path" value={publicValue('certificate_path')} onChange={value => setPublic('certificate_path', value)} />, <ConfigField key="k" label="Private key path" value={publicValue('private_key_path')} onChange={value => setPublic('private_key_path', value)} />, <ConfigField key="ca" label="CA certificate path" value={publicValue('ca_path')} onChange={value => setPublic('ca_path', value)} />, <ConfigField key="p" label="Private key passphrase" secret value={secretValue('key_passphrase')} onChange={value => setSecret('key_passphrase', value)} />)
    case 'aws-sigv4': return pair(<ConfigField key="id" label="Access key ID" value={publicValue('access_key_id')} onChange={value => setPublic('access_key_id', value)} />, <ConfigField key="sk" label="Secret access key" secret value={secretValue('secret_access_key')} onChange={value => setSecret('secret_access_key', value)} />, <ConfigField key="st" label="Session token" secret value={secretValue('session_token')} onChange={value => setSecret('session_token', value)} />, <ConfigField key="r" label="Region" value={publicValue('region')} onChange={value => setPublic('region', value)} placeholder="us-east-1" />, <ConfigField key="s" label="AWS service" value={publicValue('service')} onChange={value => setPublic('service', value)} placeholder="execute-api" />)
    case 'service-account': return pair(<ConfigField key="a" label="Account email / ID" value={publicValue('account_id')} onChange={value => setPublic('account_id', value)} />, <ConfigField key="p" label="Project / tenant ID" value={publicValue('project_id')} onChange={value => setPublic('project_id', value)} />, <ConfigField key="c" label="Credentials file path" value={publicValue('credentials_path')} onChange={value => setPublic('credentials_path', value)} />, <ConfigField key="k" label="Private key / JSON" secret value={secretValue('private_key')} onChange={value => setSecret('private_key', value)} />)
    case 'ssh': return pair(<ConfigField key="u" label="SSH username" value={publicValue('username')} onChange={value => setPublic('username', value)} />, <ConfigField key="h" label="Host and port" value={publicValue('host')} onChange={value => setPublic('host', value)} placeholder="host.example.com:22" />, <ConfigField key="k" label="Private key path" value={publicValue('private_key_path')} onChange={value => setPublic('private_key_path', value)} />, <ConfigField key="p" label="Password / key passphrase" secret value={secretValue('password')} onChange={value => setSecret('password', value)} />)
    case 'session-cookie': return pair(<ConfigField key="n" label="Cookie name" value={publicValue('cookie_name')} onChange={value => setPublic('cookie_name', value)} placeholder="session" />, <ConfigField key="v" label="Cookie value" secret value={secretValue('cookie_value')} onChange={value => setSecret('cookie_value', value)} />)
    default: return null
  }
}

function Permission({ id, label, checked, onChange }) {
  return <FormControl><Checkbox id={id} checked={checked} onChange={event => onChange(event.target.checked)} /><FormControl.Label htmlFor={id}>{label}</FormControl.Label></FormControl>
}

export default function McpServers({ servers, providers = [], onAdd, onEdit, onDuplicate, onDelete, onRevoke, onToggle, onTest, onOAuth, busy }) {
  const [adding, setAdding] = useState(false)
  const [draft, setDraft] = useState(blank)
  const [query, setQuery] = useState('')
  const [editingId, setEditingId] = useState(null)
  const filtered = useMemo(() => catalog.filter(([name, category]) => `${name} ${category}`.toLowerCase().includes(query.toLowerCase())), [query])
  const setValue = (key, value) => setDraft(current => ({ ...current, [key]: value }))
  const setPublic = (key, value) => setDraft(current => ({ ...current, public_config: { ...current.public_config, [key]: value } }))
  const setSecret = (key, value) => setDraft(current => ({ ...current, secrets: { ...current.secrets, [key]: value } }))
  function choosePreset(name, category) { setDraft({ ...blank, name: name === 'Custom server' ? '' : name, category }); setEditingId(null); setAdding(true) }
  function chooseProvider(provider) { setDraft({ ...blank, name: provider.name, category: provider.category, auth_type: provider.auth_type, public_config: { authorization_server: provider.authorization_server, authorization_endpoint: provider.authorization_endpoint, token_endpoint: provider.token_endpoint, scopes: provider.scopes, access_type: provider.access_type || '', prompt: provider.prompt || '' } }); setEditingId(null); setAdding(true) }
  function editServer(server) { setDraft({ ...blank, ...server, public_config: server.public_config || {}, permissions: server.permissions || blank.permissions, secrets: {} }); setEditingId(server.id); setAdding(true) }
  async function submit(event) { event.preventDefault(); const saved = editingId ? await onEdit(editingId, draft) : await onAdd(draft); if (saved) { setAdding(false); setDraft(blank) } }

  return <div className="settings-section">
    <SectionHeading title="MCP servers" description="Configure local and remote tools, data sources, and service integrations." actions={<Button variant="primary" leadingVisual={PlusIcon} onClick={() => choosePreset('Custom server', 'Custom')}>New MCP server</Button>} />
    <Flash className="privacy-banner"><KeyIcon size={16} /> <strong>Local, permission-controlled connections.</strong> Secrets stay in the local vault and servers remain disabled until you enable them.</Flash>

    {!adding && <>
      {providers.length > 0 && <><SubsectionHeading title="Guided connections" description="Start from a provider-specific OAuth configuration." /><div className="catalog-grid">{providers.map(provider => <button className="catalog-item" key={provider.id} onClick={() => chooseProvider(provider)}><strong>Connect {provider.name}</strong><span>Guided OAuth setup</span></button>)}</div></>}
      <TextInput aria-label="Search MCP server templates" leadingVisual={SearchIcon} block value={query} onChange={event => setQuery(event.target.value)} placeholder="Search server templates" />
      <div className="catalog-grid">{filtered.map(([name, category]) => <button className="catalog-item" key={name} onClick={() => choosePreset(name, category)}><strong>{name}</strong><span>{category}</span></button>)}</div>
      <Flash variant="warning">Registry entries are self-reported. Verify a server before installation. <Link href="https://registry.modelcontextprotocol.io/" target="_blank">Browse the official MCP Registry <LinkExternalIcon size={14} /></Link></Flash>
    </>}

    {adding && <form onSubmit={submit}>
      <SectionHeading title={editingId ? 'Edit MCP server' : 'New MCP server'} description="Use configuration supplied by the server provider. Existing secrets remain saved unless replaced." actions={<Button onClick={() => setAdding(false)}>Back</Button>} />
      <div className="form-grid">
        <ConfigField label="Display name" value={draft.name} onChange={value => setValue('name', value)} />
        <ConfigField label="Category" value={draft.category} onChange={value => setValue('category', value)} />
        <ConfigField className="wide" label="Description" value={draft.description} onChange={value => setValue('description', value)} placeholder="What this server lets Local AI do" />
        <Field label="Transport"><Select block value={draft.transport} onChange={event => setValue('transport', event.target.value)}><Select.Option value="streamable-http">Streamable HTTP (standard)</Select.Option><Select.Option value="stdio">stdio local process (standard)</Select.Option><Select.Option value="sse-legacy">HTTP + SSE (legacy)</Select.Option><Select.Option value="custom">Custom / non-standard</Select.Option></Select></Field>
        {draft.transport === 'stdio' ? <><ConfigField label="Command" value={draft.command} onChange={value => setValue('command', value)} placeholder="npx, uvx, docker, or executable path" /><ConfigField className="wide" label="Arguments" value={draft.arguments} onChange={value => setValue('arguments', value)} /><ConfigField className="wide" label="Working directory" value={draft.working_directory} onChange={value => setValue('working_directory', value)} /></> : <ConfigField label="Server endpoint" type="url" value={draft.endpoint} onChange={value => setValue('endpoint', value)} placeholder="https://server.example.com/mcp" />}
        <Field label="Authorization method" className="wide"><Select block value={draft.auth_type} onChange={event => setDraft(current => ({ ...current, auth_type: event.target.value, public_config: {}, secrets: {} }))}>{authOptions.map(([value, label]) => <Select.Option key={value} value={value}>{label}</Select.Option>)}</Select></Field>
      </div>
      {draft.auth_type !== 'none' && <div className="subsection"><SubsectionHeading title="Authorization" description="Credential values are masked and stored locally." /><AuthFields draft={draft} setPublic={setPublic} setSecret={setSecret} /></div>}
      <div className="subsection"><SubsectionHeading title="Permissions" description="Start with the minimum access this server requires." /><div className="permission-grid">{[['read','Allow read'],['write','Allow write'],['execute','Allow execute'],['network','Allow network'],['always_confirm','Confirm every tool call']].map(([key,label]) => <Permission id={`permission-${key}`} key={key} label={label} checked={Boolean(draft.permissions[key])} onChange={checked => setDraft(current => ({ ...current, permissions: { ...current.permissions, [key]: checked } }))} />)}</div></div>
      <FormControl sx={{ mt: 3 }}><Checkbox id="enable-server" checked={draft.enabled} onChange={event => setValue('enabled', event.target.checked)} /><FormControl.Label htmlFor="enable-server">Enable immediately after saving</FormControl.Label></FormControl>
      <FormActions><Button onClick={() => setAdding(false)}>Cancel</Button><Button variant="primary" disabled={busy || !draft.name.trim()} type="submit">{editingId ? 'Save changes' : 'Save MCP server'}</Button></FormActions>
    </form>}

    {!adding && <div className="data-list">{servers.length === 0 && <EmptyState title="No MCP servers configured" description="Choose a template or add a custom server." />}{servers.map(server => {
      const toggleId = `server-${server.id}-enabled`
      const menu = <ActionMenu><ActionMenu.Button size="small">More</ActionMenu.Button><ActionMenu.Overlay><ActionList><ActionList.Item onSelect={() => editServer(server)}><ActionList.LeadingVisual><PencilIcon /></ActionList.LeadingVisual>Edit</ActionList.Item><ActionList.Item onSelect={() => onDuplicate(server.id)}><ActionList.LeadingVisual><CopyIcon /></ActionList.LeadingVisual>Duplicate</ActionList.Item>{server.has_secrets && <ActionList.Item variant="danger" onSelect={() => onRevoke(server.id)}><ActionList.LeadingVisual><KeyIcon /></ActionList.LeadingVisual>Remove access</ActionList.Item>}<ActionList.Divider /><ActionList.Item variant="danger" onSelect={() => onDelete(server.id)}><ActionList.LeadingVisual><TrashIcon /></ActionList.LeadingVisual>Remove server</ActionList.Item></ActionList></ActionMenu.Overlay></ActionMenu>
      return <DataCard key={server.id} title={server.name} label={server.category} status={server.connection_status === 'connected' ? 'connected' : server.connection_status === 'error' ? 'error' : ''} meta={`${server.transport}${server.endpoint ? ` · ${server.endpoint}` : server.command ? ` · ${server.command} ${server.arguments}` : ''}`} detail={`${server.connection_status.replaceAll('-', ' ')}${server.capabilities?.tools?.length ? ` · ${server.capabilities.tools.length} tools` : ''}${server.has_secrets ? ` · ${server.secret_fields.length} secret fields saved` : ''}${server.last_error ? ` · ${server.last_error}` : ''}`} actions={<><span id={toggleId} hidden>{server.name}</span><ToggleSwitch aria-labelledby={toggleId} size="small" checked={server.enabled} onChange={checked => onToggle(server.id, checked)} disabled={busy} />{server.auth_type === 'oauth-authorization-code' && <Button size="small" leadingVisual={KeyIcon} onClick={() => onOAuth(server.id)} disabled={busy}>Connect</Button>}<Button size="small" leadingVisual={SyncIcon} onClick={() => onTest(server.id)} disabled={busy}>Test</Button>{menu}</>} />
    })}</div>}
  </div>
}
